import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider, Grid, GridItem, Box } from "@chakra-ui/react";
import NavBar from "@/components/NavBar";
import Tasks from "@/components/Tasks";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TODO w/NextJs & ChakraUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ChakraProvider>
      <Grid templateColumns={"repeat(6, 1fr)"} bg={"gray.50"}>
        <GridItem
          as={"aside"}
          colSpan={{ base: 6, md: 2, lg: 1 }}
          bg={"purple.400"}
          minHeight={{ md: "100vh"}}
          p={{ base: "20px", md: "30px"}}
        >
          <Sidebar />
        </GridItem>
        <GridItem as={"main"} colSpan={{ base: 6, md: 4, lg: 5 }} px={"40px"}>
          <NavBar />
          <Tasks />
          {children}
        </GridItem>
      </Grid>
    </ChakraProvider>
  );
}
